# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/chris/Documents/GitHub/Haushaltsbuch/ui/dialogNewData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(11)
        font.setBold(True)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: #313a46;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxKategorie = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(11)
        font.setBold(True)
        self.comboBoxKategorie.setFont(font)
        self.comboBoxKategorie.setStyleSheet("QComboBox {\n"
"    color: #fff;\n"
"}\n"
"\n"
"QComboBox:items {\n"
"    color: #fff;\n"
"}\n"
"\n"
"QListView {\n"
"    color: #fff;\n"
"}   \n"
"\n"
"QLineEdit {\n"
"    color: #fff;\n"
"}")
        self.comboBoxKategorie.setObjectName("comboBoxKategorie")
        self.comboBoxKategorie.addItem("")
        self.comboBoxKategorie.setItemText(0, "")
        self.gridLayout.addWidget(self.comboBoxKategorie, 2, 0, 1, 1)
        self.lineEditSelectedFile = QtWidgets.QLineEdit(Dialog)
        self.lineEditSelectedFile.setStyleSheet("color: #fff;")
        self.lineEditSelectedFile.setObjectName("lineEditSelectedFile")
        self.gridLayout.addWidget(self.lineEditSelectedFile, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #fff;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.toolButtonFileDialog = QtWidgets.QToolButton(Dialog)
        self.toolButtonFileDialog.setObjectName("toolButtonFileDialog")
        self.gridLayout.addWidget(self.toolButtonFileDialog, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(11)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #fff;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButtonAbbrechen.setFont(font)
        self.pushButtonAbbrechen.setStyleSheet("QPushButton {\n"
"    background-color:  #6d6d6d;\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #e0e1e3;\n"
"    color: #fff;\n"
"}")
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.gridLayout_2.addWidget(self.pushButtonAbbrechen, 1, 0, 1, 1)
        self.pushButtonSpeichern = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cabin")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButtonSpeichern.setFont(font)
        self.pushButtonSpeichern.setStyleSheet("QPushButton {\n"
"    background-color:  #6d6d6d;\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #e0e1e3;\n"
"    color: #fff;\n"
"}")
        self.pushButtonSpeichern.setObjectName("pushButtonSpeichern")
        self.gridLayout_2.addWidget(self.pushButtonSpeichern, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Datei einlesen"))
        self.toolButtonFileDialog.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Kategorie:"))
        self.pushButtonAbbrechen.setText(_translate("Dialog", "Abbrechen"))
        self.pushButtonSpeichern.setText(_translate("Dialog", "Fertig"))
